language: c++

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
          env: COMPILER=g++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - clang-6.0
          env: COMPILER=clang++-6.0

notification:
  email: false

befor_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq cppcheck qt5-default qtbase5-dev lcov

script:
- cppcheck --quiet --error-exitcode=1 .
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Coverage .. && make -j4
- cd src
- ./travis_test
- cd ../test
- ./tests
- cd ..
- make coverage

